services:
  - type: web
    name: solo-pizzeria
    runtime: static
    buildCommand: echo "No build required"
    staticPublishPath: .
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: "true"
